name: pharmacy
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^1.6.0
  page_transition: ^1.1.5
  cached_network_image: ^2.0.0
  flutter_barcode_scanner: ^1.0.1
  sqflite: ^1.3.0+2
  shared_preferences: ^0.5.7+3
  flutter_svg: ^0.17.3+1
  http: ^0.12.0+2
  shimmer: ^1.1.1
  rxdart: ^0.18.0
  yandex_mapkit: ^0.3.9
  permission_handler: ^3.2.2
  geolocator: ^5.3.1
  mask_text_input_formatter: ^1.0.7
  flutter_datetime_picker: ^1.3.8
  webview_flutter: ^0.3.22+1
  url_launcher: ^5.4.11

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/menu/
    - assets/map/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
    - family: TTCommons
      fonts:
        - asset: assets/fonts/TTCommons-DemiBold.ttf
