name: pharmacy
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^1.6.0
  page_transition: ^1.1.5
  cached_network_image: ^2.2.0+1
  flutter_barcode_scanner: ^1.0.1
  sqflite: ^1.3.0+2
  shared_preferences: ^0.5.7+3
  flutter_svg: ^0.18.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/menu/


  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
    - family: TTCommons
      fonts:
        - asset: assets/fonts/TTCommons-DemiBold.ttf
