name: pharmacy
description: A new Flutter application.

version: 1.1.4+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^3.0.1
  cached_network_image: ^3.0.0
  barcode_scan: ^3.0.1
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.6
  flutter_svg:
  http: ^0.13.3
  shimmer: ^2.0.0
  rxdart: ^0.27.1
  yandex_mapkit: ^0.4.0
  permission_handler: ^7.2.0
  geolocator: ^7.1.0
  flutter_datetime_picker: ^1.5.0
  url_launcher: ^6.0.6
  cupertino_icons: ^0.1.2
  lottie: ^1.0.1
  package_info: ^2.0.2
  firebase_messaging: ^10.0.1
  firebase_core: ^1.2.1
  flutter_local_notifications: ^5.0.0
  flutter_picker: ^2.0.1
  carousel_slider: ^3.0.0
  device_info: ^2.0.2
  app_settings: ^4.1.0
  flutter_udid: ^2.0.0
  simple_html_css: ^3.0.1
  webview_flutter: ^2.0.8
  appmetrica_sdk: ^0.0.7
  page_transition: ^2.0.2
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/menu/
    - assets/map/
    - assets/anim/
    - assets/icons/
    - assets/img/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
