name: pharmacy
description: A new Flutter application.

version: 1.1.4+14

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^1.6.0
  page_transition: ^1.1.7+2
  cached_network_image: ^2.0.0
  barcode_scan: ^3.0.1
  sqflite: ^1.3.0+2
  shared_preferences: ^0.5.7+3
  flutter_svg: ^0.19.3
  http: ^0.12.0+2
  shimmer: ^1.1.1
  rxdart: ^0.20.0
  yandex_mapkit: ^0.4.1
  permission_handler: ^3.2.2
  geolocator: ^5.3.1
  mask_text_input_formatter: ^1.0.7
  flutter_datetime_picker: ^1.5.0
  url_launcher: ^5.4.11
  rxbus: ^0.0.2
  cupertino_icons: ^0.1.2
  web_socket_channel: ^1.1.0
  lottie: ^0.6.0
  firebase_messaging: ^7.0.3
  package_info: ^0.4.1
#  selectable_autolink_text: ^1.3.3
  flutter_local_notifications: ^1.4.4+4
  flutter_picker: ^1.1.5
  carousel_slider: ^2.3.1
  android_intent: ^0.3.7+6
  device_info: ^0.4.2+9
  app_settings: ^4.0.4
  flutter_udid: ^1.0.1
  simple_html_css: ^2.0.2
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/menu/
    - assets/map/
    - assets/anim/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
    - family: TTCommons
      fonts:
        - asset: assets/fonts/TTCommons-DemiBold.ttf
